
name: .NET build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup NuGet Source for GitHub Packages
      run: dotnet nuget add source "https://nuget.pkg.github.com/AuthenticCod3/index.json" -n github -u "jpereira29" -p "${{ secrets.GH_PACKAGES_TOKEN }}" --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
